version: '3'

services:
  db_ref:
    restart: always
    container_name: db_ref
    image: postgres:13.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - dbrefdata:/var/lib/postgresql/data/

  ref_backend:
    container_name: ref_backend
    hostname: ref_backend
    build: .
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_LOCAL_PORT: 5432
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db_ref
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/public/static
    restart: on-failure
  nginx_ref:
    build: ./nginx
    volumes:
      - static_volume:/app/public/static
    ports:
      - "8080:80"
    depends_on:
      - ref_backend

volumes:
  dbrefdata:
  static_volume: