# Generated by Django 5.1.3 on 2024-12-02 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_activeuserinvitecode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeuserinvitecode',
            name='active_invite_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.invitecode', verbose_name='Активированный инвайт-код'),
        ),
        migrations.AlterField(
            model_name='activeuserinvitecode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_invite', to=settings.AUTH_USER_MODEL, verbose_name='Юзер'),
        ),
    ]
