# Generated by Django 5.1.3 on 2024-11-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
