# Generated by Django 5.1.3 on 2024-12-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_refuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeauth',
            name='code',
            field=models.SmallIntegerField(verbose_name='Код'),
        ),
    ]
