# Generated by Django 5.1.3 on 2024-12-01 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_codeauth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeauth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
    ]
