# Generated by Django 5.1.3 on 2024-12-01 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_codeauth_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='refuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='refuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
