# Generated by Django 5.1.3 on 2024-12-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_refuser_created_at_refuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя и фамилий'),
        ),
    ]
