# Generated by Django 5.1.3 on 2024-12-01 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_refuser_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='refuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='refuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='refuser',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='refuser',
            name='password',
            field=models.CharField(default=datetime.datetime(2024, 12, 1, 10, 2, 30, 589764, tzinfo=datetime.timezone.utc), max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
