# Generated by Django 5.1.3 on 2024-12-01 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_codeauth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeauth',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
